### ISSUE TITLE
need the dataset...

### ISSUE THREAD

**Issue by Sajid576** [FMZennaro/CTF-SQL#3]
Can u plz upload/ email me the dataset......? I need it right now............. 
mail: sajidahmed696@gmail.com

**Comment by FMZennaro** [comment]
Hey Sajid,
There is no static dataset. The agent learns online generating dynamically its actions and the responses of the environment. For reproducibility, you can set a seed in the random generator underlying the simulation. You can also, of course, collect data (storing trajectories in a replay buffer) and use it to train an agent offline.
