### ISSUE TITLE
ModuleNotFoundError: No module named 'ctfsql'

### ISSUE THREAD

**Issue by sataketatsuya** [FMZennaro/CTF-SQL#4]
On my local environment, I found an error which is **ModuleNotFoundError: No module named 'ctfsql'**  in _Simulation2_b32 - Training.ipynb file.  How can I resolve this error?
I could not find a ctfsql module in this project and then I have no idea to resolve it. I need your help, please.
<img width="948" alt="スクリーンショット 2021-10-04 16 43 32" src="https://user-images.githubusercontent.com/49749442/135813531-39139bac-1de7-496a-b51e-a33be1de2ed4.png">

**Comment by FMZennaro** [comment]
The ctfsql module contains the OpenAI gym environment used in the simulation. You can find and install it from https://github.com/avalds/gym-CTF-SQL

Following your issue, I have also updated the README for the *CTF-SQL* and the *gym-CTF-SQL* projects; that hopefully offers a little bit more direction in setting up the environment and re-running the simulations. :)

**Comment by sataketatsuya** [comment]
@FMZennaro 
thanks!!! I installed gym-CTF-SQL and my environment worked. :)
